version: "3"
services:
  latex:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
      - ./.latexmkrc:/root/.latexmkrc
    command: >
      sh -c 'npm i -D && sleep infinity'
    tty:
      true
